on:
  pull_request_review:
    types: [edited, submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create test branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.head_ref }}-test

      - name: Install Compucorp-Stripe dependencies
        working-directory: ${{ env.CIVICRM_EXTENSIONS_DIR }}/uk.co.compucorp.stripe
        run: composer install

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: 'Your commit message'
          add: '*.js'
          push: true

