name: Build Test Branch

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create test branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.head_ref }}-test

      - name: Install dependencies
        run: composer install

      - name: Set environment variables
        run: |
          echo PUBLISHABLE_KEY="${{ secrets.PUBLISHABLE_KEY }}" >> .env
          echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
          echo URL_SITE="${{ secrets.URL_SITE }}" >> .env
          echo TEST_PUBLISHABLE_KEY="${{ secrets.TEST_PUBLISHABLE_KEY }}" >> .env
          echo TEST_SECRET_KEY="${{ secrets.TEST_SECRET_KEY }}" >> .env
          echo TEST_URL_SITE="${{ secrets.TEST_URL_SITE }}" >> .env
          echo TEST_MODE=1 >> .env

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ github.head_ref }}-test
          message: 'Add files for deploy'
          add: 'vendor/* .env -f'
          push: true