name: Build Initial

on:
  release: 
    types: ['created']
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    
    name: Release Upload Release Asset
    runs-on: ubuntu-latest
    container: php:7.2.30

    steps:

      - name: Build tarball Fake for test
        shell: bash
        run: |
          truncate -s 60M compuclient-${{ github.event.release.tag_name }}.txt
                    
      - name: Upload Release Asset
        id: upload-release-asset
        continue-on-error: true
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url}} 
          asset_path: ./compuclient-${{ github.event.release.tag_name }}.txt
          asset_name: compuclient-${{ github.event.release.tag_name }}.txt
          asset_content_type: text/plain

      - name: Upload Release Asset (retry)
        id: upload-release-asset-retry
        if: steps.upload-release-asset.outcome == 'failure'
        continue-on-error: true
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url}}
          asset_path: ./compuclient-${{ github.event.release.tag_name }}.txt
          asset_name: compuclient-${{ github.event.release.tag_name }}.txt
          asset_content_type: text/plain
